---
exclude: .*csv
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  #- id: check-yaml
  - id: check-byte-order-marker
  - id: check-merge-conflict
  - id: check-ast
  - id: check-builtin-literals
  - id: debug-statements
  - id: requirements-txt-fixer
  - id: fix-encoding-pragma
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
  - id: bandit
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.2.0
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
  - id: remove-tabs
- repo: https://github.com/IBM/detect-secrets
  rev: 0.13.1+ibm.50.dss
  hooks:
  - id: detect-secrets
    args: [--baseline, .secrets.baseline]
