---
name: Pull Request Labeler

on: [pull_request] # yamllint disable-line rule:truthy

jobs:
  label:
    name: auto label
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      continue-on-error: true
      with:
        repo-token: ${{ secrets.AUTO_MERGE_TOKEN }}
    - uses: TimonVS/pr-labeler-action@v3.1.0
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
